# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: undefined
email: mitch.mclaughlin1@gmail.com 
description: > # this means to ignore newlines until "

theme: jekyll-theme-tactile

baseurl: "" # the subpath of your site, e.g. /blog

url: "https://mitchellmclaughlin.com" # the base hostname & protocol for your site
twitter_username: m23mclaughlin
github_username:  m23mclaughlin

#instagram_username: m23mclaughlin
#facebook_username: okaymitch
#quora_username: mitchell-mclaughlin-1
#linkedin_username: mitchellmclaughlin
#medium_username: m23mclaughlin
#snapchat_username: m23mclaughlin
#tumblr_username: m23mclaughlin.tumblr.com
#reddit_username: m23mclaughlin
#venmo_username: mitch-mclaughlin

# Build settings
markdown: kramdown

gems:
 - jekyll-seo-tag
 - jekyll-feed
